class MechSwitchableAmmo : MechAmmo
{
	string loadedName;
	class<MechProjectile> ammoProj;
	
	override void Defaults()
	{
		super.Defaults();
		template = true;
	}
	
	override void getDescription(out string flavorText, out Array<String> statName, out Array<String> statValue, DrivableMech mechInfo)
	{
		super.getDescription(flavorText, statName, statValue);
		if(!ammoProj) return;
		
		statName.Push(" ");
		statValue.Push(" ");
		
		let projDefs = GetDefaultByType(ammoProj);
		
		statName.Push("DAMAGE");
		statValue.Push(String.Format("%.2f", (projDefs.trueDamage * MechHardpoint.DMGSCALE) ));
		if(projDefs.minRange > 0)
		{
			statName.Push("MIN RANGE");
			statValue.Push(String.Format("%d", projDefs.minRange));
		}
		statName.Push("MAX RANGE");
		statValue.Push(String.Format("%d", projDefs.maxRange));
		statName.Push("OPTIMAL RANGE");
		statValue.Push(String.Format("%d", projDefs.maxRange * 0.5));
	}
}

class SRMAmmo : MechAmmo
{
	override void Defaults()
	{
		damagable = true;
		displayName = "SRM Ammo";
		maxAmmo = 120;
		weight = 1.0;
		size = 1.0;
		explosionDamage = 2;
		
		SetupAmmo();
	}
}
class SSRMAmmo : SRMAmmo
{
	override void Defaults()
	{
		super.Defaults();
		displayName = "SSRM Ammo";
	}
}

class MRMAmmo : MechAmmo
{
	override void Defaults()
	{
		damagable = true;
		displayName = "MRM Ammo";
		maxAmmo = 340;
		weight = 1.0;
		size = 1.0;
		explosionDamage = 1;
		
		SetupAmmo();
	}
}

class LRMAmmo : MechAmmo
{
	override void Defaults()
	{
		damagable = true;
		displayName = "LRM Ammo";
		maxAmmo = 240;
		weight = 1.0;
		size = 1.0;
		explosionDamage = 1;
		
		SetupAmmo();
	}
}

class AC2Ammo : MechAmmo
{
	override void Defaults()
	{
		damagable = true;
		displayName = "AC/2 Ammo";
		maxAmmo = 50;
		weight = 1.0;
		size = 1.0;
		explosionDamage = 2;
		
		SetupAmmo();
	}
}
class AC5Ammo : MechAmmo
{
	override void Defaults()
	{
		damagable = true;
		displayName = "AC/5 Ammo";
		maxAmmo = 25;
		weight = 1.0;
		size = 1.0;
		explosionDamage = 5;
		
		SetupAmmo();
	}
}
class AC10Ammo : MechAmmo
{
	override void Defaults()
	{
		damagable = true;
		displayName = "AC/10 Ammo";
		maxAmmo = 10;
		weight = 1.0;
		size = 1.0;
		explosionDamage = 10;
		
		SetupAmmo();
	}
}
class AC20Ammo : MechAmmo
{
	override void Defaults()
	{
		damagable = true;
		displayName = "AC/20 Ammo";
		maxAmmo = 5;
		weight = 1.0;
		size = 1.0;
		explosionDamage = 20;
		
		SetupAmmo();
	}
}
class MGAmmo : MechAmmo
{
	override void Defaults()
	{
		damagable = true;
		displayName = "MACHINEGUN AMMO";
		maxAmmo = 1000;
		weight = 1.0;
		size = 1.0;
		explosionDamage = 0.04;
		
		SetupAmmo();
	}
}

class UAC2Ammo : AC2Ammo 
{
	override void Defaults()
	{
		super.Defaults();
		displayName = "UAC/2 Ammo";
	}
}
class UAC5Ammo : AC5Ammo
{
	override void Defaults()
	{
		super.Defaults();
		displayName = "UAC/5 Ammo";
	}
}
class UAC10Ammo : AC10Ammo
{
	override void Defaults()
	{
		super.Defaults();
		displayName = "UAC/10 Ammo";
	}
}
class UAC20Ammo : AC20Ammo
{
	override void Defaults()
	{
		super.Defaults();
		displayName = "UAC/20 Ammo";
	}
}

class GaussAmmo : MechAmmo
{
	override void Defaults()
	{
		damagable = true;
		displayName = "Gauss Ammo";
		maxAmmo = 8;
		weight = 1.0;
		size = 1.0;
		explosionDamage = 0;
		
		SetupAmmo();
	}
}

class AMSAmmo : MechAmmo
{
	override void Defaults()
	{
		damagable = true;
		displayName = "AMS AMMO";
		maxAmmo = 1000;
		weight = 1.0;
		size = 1.0;
		explosionDamage = 0.01;
		
		SetupAmmo();
	}
}
class AMSAmmoHalf : AMSAmmo
{
	override void Defaults()
	{
		super.Defaults();
		displayName = "AMS AMMO 1/2";
		maxAmmo *= 0.5;
		weight = 0.5;
		baseAmmoClass = "AMSAmmo";
		
		SetupAmmo();
	}
}

class STDATMAmmo : MechSwitchableAmmo
{
	override void Defaults()
	{
		super.Defaults();
		template = false;
		displayName = "ATM AMMO (Standard)";
		maxAmmo = 105;
		weight = 1.0;
		explosionDamage = 2;
		ammoProj = "MechATM_STD";
		loadedName = "\c[Gold][STD]";
		
		SetupAmmo();
	}
}
class ERATMAmmo : MechSwitchableAmmo
{
	override void Defaults()
	{
		super.Defaults();
		template = false;
		displayName = "ATM AMMO (Extended Range)";
		maxAmmo = 105;
		weight = 1.0;
		explosionDamage = 1;
		ammoProj = "MechATM_ER";
		loadedName = "\c[Gold][ER]";
		
		SetupAmmo();
	}
}
class HEATMAmmo : MechSwitchableAmmo
{
	override void Defaults()
	{
		super.Defaults();
		template = false;
		displayName = "ATM AMMO (High Explosive)";
		maxAmmo = 105;
		weight = 1.0;
		explosionDamage = 3;
		ammoProj = "MechATM_HE";
		loadedName = "\c[Gold][HE]";
		
		SetupAmmo();
	}
}